Repository owncloud/owncloud-design-system, pull requests merged in 2019-05, with the labels that each got.

#264 Created oc-file-actions class and changed colour of actions bar
  src/patterns/OcFileActions.vue
  src/styles/_owncloud.scss
  src/styles/theme/oc-file-actions.scss
Labels: 3 - To Review, enhancement

#260 Added placeholder and spinner when loading
  src/elements/OCAvatar.vue
  src/pages/Files.vue
Labels: enhancement

#236 Add oc-grid element
  src/elements/OcButton.vue
  src/elements/OcGrid.vue
  src/pages/Files.vue
  src/patterns/OcSearchBar.vue
  src/styles/theme/oc-button.scss
  src/styles/theme/oc-search.scss
Labels: enhancement

#245 Added slots
  src/elements/OCDrop.vue
  src/elements/OcButton.vue
  src/elements/OcTabItem.vue
  src/elements/_OcAccordionItem.vue
  src/elements/_OcSidebarNavDivider.vue
  src/elements/_OcSidebarNavHeader.vue
  src/elements/_OcSidebarNavItem.vue
  src/pages/Files.vue
  src/pages/Login.vue
  src/patterns/OcAccordion.vue
  src/patterns/OcAppLayout.vue
  src/patterns/OcApplicationMenu.vue
  src/patterns/OcFileActions.vue
  src/patterns/_OcTopBarItem.vue
Labels: 3 - To Review

#270 Added message to notifications and moved texts to slots
  src/elements/OCNotificationMessage.vue
  src/elements/OCNotifications.vue
Labels: 3 - To Review, enhancement

#274 Added class to notification title
  src/elements/OCNotificationMessage.vue
Labels: 3 - To Review, enhancement

#283 Fixed value and documentation
  src/elements/OcSwitch.vue
Labels: 3 - To Review, bug

#286 Changed switch model type from String to Number
  src/elements/OcSwitch.vue
Labels: 3 - To Review, bug

#290 Upgraded dependencies
  package.json
  yarn.lock
Labels: 3 - To Review, dependencies

#302 Add optional home-item in breadcrumb
  src/elements/OcBreadcrumb.vue
  src/pages/Files.vue
Labels: enhancement

#306 Add OcAppBar Component wrapper
  src/pages/Files.vue
  src/patterns/OcAppBar.vue
Labels: 3 - To Review

#310 Update multiple dependencies
  package.json
  yarn.lock
Labels: dependencies
