Repository owncloud/owncloud-design-system, pull requests merged in 2019-07, with the labels that each got.

#375 Feature/ellipse breadcrumb
  src/assets/icons/add.svg
  src/assets/icons/chevron_left.svg
  src/assets/icons/chevron_right.svg
  src/assets/icons/expand_less.svg
  src/assets/icons/expand_more.svg
  src/assets/icons/more_horiz.svg
  src/assets/icons/more_vert.svg
  src/elements/OcBreadcrumb.vue
  src/pages/Files.vue
  src/styles/_owncloud.scss
  src/styles/theme/oc-breadcrumb.scss
Labels: 3 - To Review, enhancement

#382 Added helper class align-self-center
  src/styles/theme/helper.scss
Labels: 3 - To Review, enhancement

#381 Autocomplete dropdown class
  src/patterns/OcAutocomplete.vue
Labels: 3 - To Review, enhancement

#388 Update dependencies 20190702
  package.json
  yarn.lock
Labels: 3 - To Review

#389 Expand autocomplete list
  src/patterns/OcAutocomplete.vue
  src/styles/theme/oc-autocomplete.scss
Labels: bug

#392 Danger variation for button
  src/elements/OcButton.vue
  src/styles/theme/oc-button.scss
Labels: 3 - To Review, enhancement

#403 Added repeat icon
  src/assets/icons/repeat.svg
Labels: 3 - To Review

#405 Fix colour of repeat icon
  src/assets/icons/repeat.svg
Labels: 3 - To Review

#406 Changed alert close icon element to link
  src/elements/OCNotificationMessage.vue
Labels: 3 - To Review, enhancement

#394 Change colour of text-meta on hover to inverted
  src/patterns/OcAutocomplete.vue
  src/styles/theme/oc-autocomplete.scss
Labels: 3 - To Review, enhancement

#416 oc-checkbox: stop event propagation of the click event
  src/elements/OcCheckbox.vue
Labels: 3 - To Review

#414 Allow closing of drop on click
  src/elements/OCDrop.vue
  src/styles/theme/oc-autocomplete.scss
Labels: 3 - To Review, enhancement

#424 Add zoom-in/out icons
  src/assets/icons/zoom_in.svg
  src/assets/icons/zoom_out.svg
Labels: enhancement

#419 Added transition to messages
  src/elements/OCNotificationMessage.vue
  src/elements/OCNotifications.vue
  src/styles/theme/oc-alert.scss
Labels: 3 - To Review, enhancement

#435 Fix two 1s in more result text in autocomplete
  src/patterns/OcAutocomplete.vue
Labels: 3 - To Review

#438 Fixed off state of switch
  src/styles/theme/oc-switch.scss
Labels: 3 - To Review
