Repository owncloud/owncloud-design-system, pull requests merged in 2019-08, with the labels that each got.

#452 Reworked avatar
  src/elements/OCAvatar.vue
  src/styles/theme/oc-avatar.scss
Labels: 3 - To Review

#456 Added person and group icons
  src/assets/icons/group.svg
  src/assets/icons/person.svg
Labels: 3 - To Review

#457 Added src prop to avatar
  src/elements/OCAvatar.vue
Labels: 3 - To Review

#458 Added inverted color to icon in autocomplete
  src/styles/theme/oc-autocomplete.scss
Labels: 3 - To Review

#460 Add lock icons
  src/assets/icons/lock.svg
  src/assets/icons/lock_open.svg
Labels: enhancement

#466 Remove oc-file-actions - implemented in phoenix itself
  src/patterns/OcFileActions.vue
Labels: 3 - To Review

#468 Add copy to clipboard icon
  src/assets/icons/copy_top_clipboard.svg
Labels: 3 - To Review

#467 feature/datepicker
  package.json
  src/elements/OcDatepicker.vue
  src/styles/_owncloud.scss
  src/styles/theme/oc-datepicker.scss
  yarn.lock
Labels: 3 - To Review

#453 Added xsmall margin
  src/styles/_owncloud.scss
  src/styles/theme/margin.scss
  src/tokens/margins.yml
Labels: 3 - To Review, enhancement
