Repository owncloud/owncloud-design-system, pull requests merged in 2019-04, with the labels that each got.

#180 Removed type string from oc-text-input
  src/elements/OcTextInput.vue
Labels: bug

#181 Removed v-model and reused methods from oc-text-input
  src/elements/OcTextarea.vue
Labels: bug

#186 add oc-user
  src/patterns/OcUser.vue
Labels: enhancement

#185 introduce pages
  config/docs.config.js
  docs/components/status/Components.vue
  docs/pages.md
  src/pages/Files.vue
  src/pages/Login.vue
Labels: enhancement

#192 Bugfix/reset-search
  src/patterns/OcSearchBar.vue
Labels: bug

#196 Added translation
  src/elements/OcMenuItem.vue
  src/patterns/OcMenu.vue
Labels: bug

#187 Allow passign in value to ocRadio
  src/elements/OcRadio.vue
Labels: enhancement

#209 Fixed disappearing button
  docs/components/Preview.js
Labels: bug

#208 Downgraded vue-styleguidist
  package.json
  yarn.lock
Labels: bug

#210 Move buttons next to avatar
  src/patterns/OcUser.vue
Labels: bug

#198 Created upload-menu component
  src/patterns/OcUploadMenu.vue
Labels: enhancement

#215 use aria-label in button
  src/elements/OcButton.vue
Labels: accessibility

#197 Created filterMenuItem component
  src/elements/OcCheckbox.vue
  src/elements/OcFilterMenuItem.vue
Labels: enhancement

#226 Introduce OCDrop Element
  src/elements/OCDrop.vue
  src/elements/OcCheckbox.vue
  src/elements/OcNav.vue
  src/elements/OcNavItem.vue
  src/pages/Files.vue
  src/patterns/OcMenu.vue
  src/patterns/OcSearchBar.vue
  src/styles/theme/oc-checkbox.scss
  src/styles/theme/oc-search.scss
Labels: enhancement

#230 Created oc-dropzone component
  src/elements/_OCDropzone.vue
  src/styles/_owncloud.scss
  src/styles/theme/oc-dropzone.scss
Labels: enhancement

#244 Added slot for extra content
  src/elements/OcNavItem.vue
Labels: enhancement

#254 Use node 11 images in drone ...
  .drone.yml
Labels: 3 - To Review

#253 Loading string can be set via a property + changing the model is now …
  src/patterns/OcAutocomplete.vue
Labels: 3 - To Review

#259 Add overflow hidden to center app layout element
  src/patterns/OcAppLayout.vue
Labels: 3 - To Review
