Repository owncloud/owncloud-design-system, pull requests merged in 2019-06, with the labels that each got.

#317 IE11 support
  src/elements/OcFile.vue
  src/styles/theme/login.scss
  src/styles/theme/oc-file.scss
  src/styles/theme/oc-search.scss
  src/styles/theme/oc-topbar.scss
Labels: 3 - To Review

#321 [IE11] Give topbar a min height
  src/styles/theme/oc-topbar.scss
Labels: bug

#322 Removed pointer from user
  src/styles/theme/oc-topbar.scss
Labels: 3 - To Review

#337 Added notification bell icon
  src/assets/icons/bell.svg
Labels: 3 - To Review

#349 Update deps 20190614
  package.json
  yarn.lock
Labels: dependencies

#323 New App-Bar
  src/styles/_owncloud.scss
  src/styles/theme/main.scss
  src/styles/theme/oc-app-bar.scss
  src/styles/theme/oc-app-container.scss
  src/styles/theme/oc-scroll.scss
Labels: 3 - To Review, enhancement

#358 Add cursor helper class
  src/styles/_owncloud.scss
  src/styles/theme/helper.scss
Labels: 3 - To Review, enhancement

#364 Show exact matches in ocAutocomplete
  src/patterns/OcAutocomplete.vue
Labels: bug

#356 Align ocDrop Element to its boundary
  src/elements/OCDrop.vue
Labels: 3 - To Review, bug, enhancement

#366 [Upstream] Add stopClassPropagation to help pattern styling
  src/elements/OcButton.vue
  src/elements/OcTextInput.vue
Labels: enhancement

#373 force body inherit overflow and height values in docs.styles
  docs/docs.styles.scss
Labels: bug

#365 Removed right margin from sidebar close button
  src/patterns/OcAppSideBar.vue
Labels: 3 - To Review, enhancement
