Repository owncloud/owncloud-design-system, pull requests merged in 2020-04, with the labels that each got.

#703 Use webpack-node-externals and adjust other dependencies
  build/webpack.system.conf.js
  package.json
  yarn.lock
Labels: 3 - To Review

#705 Remove lodash dependency
  docs/components/status/Components.vue
  docs/components/tokens/All.vue
  docs/components/tokens/Color.vue
  docs/components/tokens/FontSize.vue
  docs/components/tokens/Spacing.vue
  docs/utils/orderBy.js
  package.json
  src/patterns/OcAutocomplete.vue
  src/utils/uniqueId.js
  yarn.lock
Labels: 3 - To Review

#706 Fixed search bar layout
  changelog/unreleased/706-1
  changelog/unreleased/706-2
  src/elements/OcTextInput.vue
  src/patterns/OcSearchBar.vue
  src/styles/theme/oc-search.scss
Labels: 3 - To Review, bug, enhancement

#710 Fix OcAutocomplete
  changelog/unreleased/710
  src/patterns/OcAutocomplete.vue
Labels: 3 - To Review

#711 Preparation for release 1.2.2
  changelog/1.2.2_2020-04-08/710
  package.json
Labels: 3 - To Review

#709 Run unit tests in drone
  .drone.star
  .eslintignore
  .gitignore
  docs/components/tokens/All.spec.js
  docs/components/tokens/Color.spec.js
  docs/components/tokens/FontSize.spec.js
  docs/components/tokens/Spacing.spec.js
  docs/utils/activeNav.spec.js
  docs/utils/filterSearch.spec.js
  docs/utils/statusLabels.spec.js
  jest.conf.js
  package.json
  src/elements/OCAlert.spec.js
  src/elements/OCAlert.vue
  src/elements/__snapshots__/OCAlert.spec.js.snap
  test/unit/.eslintrc
  test/unit/index.js
  test/unit/setup.js
  yarn.lock
Labels: 3 - To Review

#723 Added modal component
  changelog/unreleased/modal_component
  jest.conf.js
  jest.setup.js
  package.json
  src/assets/icons/warning.svg
  src/elements/OcIcon.vue
  src/elements/OcModal.spec.js
  src/elements/OcModal.vue
  src/elements/__snapshots__/OcModal.spec.js.snap
  src/styles/_owncloud.scss
  src/styles/theme/oc-modal.scss
  src/tokens/margins.yml
  src/tokens/paddings.yml
  yarn.lock
Labels: 3 - To Review, enhancement

#730 Extended modal with an input
  changelog/unreleased/extended-modal-with-input
  src/elements/OcModal.spec.js
  src/elements/OcModal.vue
  src/elements/__snapshots__/OcModal.spec.js.snap
  src/styles/theme/oc-modal.scss
Labels: 3 - To Review, enhancement
