Repository owncloud/owncloud-design-system, pull requests merged in 2021-07, with the labels that each got.

#1456 [CI] start the build steps only after unit tests have succeded
  .drone.star
Labels: QA:team

#1451 Added unit tests for _OcNavbarItem component
  src/components/OcNavbarItem.spec.js
Labels: QA:team

#1452 added unit tests for OcNavbar component
  src/components/OcNavbar.spec.js
  src/components/OcNavbar.vue
Labels: QA:team

#1449 Added unit tests for OcLoader component
  src/components/OcLoader.spec.js
Labels: QA:team

#1440 added unit tests for OcAutocomplete component
  src/components/OcAutocomplete.spec.js
Labels: QA:team

#1450 Added unit tests for OcLogo component
  src/components/OcLogo.spec.js
Labels: QA:team

#1381 [tests-only] added unit tests for accordion item
  src/components/OcAccordionItem.spec.js
  src/components/OcAccordionItem.vue
Labels: QA:team

#1474 [unit-tests] added unit tests for OcNav component
  src/components/OcNav.spec.js
Labels: QA:team

#1475 [unit-tests] added unit tests for OcNavItem item component
  src/components/OcNavItem.spec.js
  src/components/OcNavItem.vue
Labels: QA:team

#1490 [unit-tests] Added unit tests for OcRadio component
  src/components/OcRadio.spec.js
Labels: QA:team

#1489 [unit-tests] Added unit tests for OcNotifications component
  src/components/OcNotifications.spec.js
  src/components/OcNotifications.vue
Labels: QA:team

#1478 feat: add page size component
  changelog/unreleased/change-remove-select-model
  changelog/unreleased/enhancement-add-page-size
  src/components/OcSelect.vue
  src/components/page-size/OcPageSize.spec.js
  src/components/page-size/OcPageSize.vue
  src/tokens/ods/size.yaml
Labels: enhancement

#1495 [unit-tests] added unit tests for OcSearchBar component
  src/components/OcSearchBar.spec.js
  src/components/OcSearchBar.vue
Labels: QA:team

#1498 [unit-tests] Added more unit tests for OcTextInput component
  src/components/OcTextInput.spec.js
Labels: QA:team

#1504 Reuse selectors variables and wrapper function inside pagination spec file
  src/components/pagination/OcPagination.spec.js
Labels: QA:team

#1476 [unit-tests] added unit tests for OcNotificationMessage component
  src/components/OcNotificationMessage.spec.js
  src/components/OcNotificationMessage.vue
Labels: QA:team

#1510 [unit-tests] Added unit tests for OcUser component
  src/components/OcUser.spec.js
  src/components/OcUser.vue
Labels: QA:team

#1528 Fix replace regex for ids in template of OcTableFiles
  changelog/unreleased/bugfix-tablefiles-id
  src/components/table/OcTableFiles.spec.js
  src/components/table/OcTableFiles.vue
Labels: 3 - To Review

#1521 Introduce search:input event to select, deprecate autocomplete and add OcRecipient
  .stylelintrc.json
  changelog/6.4.0_2021-05-06/enhancement-oc-select-a11y
  changelog/unreleased/enhancement-deprecate-autocomplete
  changelog/unreleased/enhancement-oc-recipient
  changelog/unreleased/enhancement-select-search-input
  package.json
  src/assets/icons/user_remote.svg
  src/components/OcAutocomplete.vue
  src/components/OcRadio.spec.js
  src/components/OcRecipient/OcRecipient.spec.js
  src/components/OcRecipient/OcRecipient.vue
  src/components/OcSelect.vue
  src/components/table/OcTableFiles.spec.js
  src/styles/styles.scss
  src/styles/theme/_oc-tabbed.scss
  src/styles/theme/_variables.scss
  src/styles/theme/oc-datepicker.scss
  src/styles/theme/oc-loader.scss
  src/styles/theme/oc-progress-pie.scss
  src/styles/theme/oc-scroll.scss
  src/styles/theme/oc-spacing.scss
  src/styles/theme/oc-spinner.scss
  src/styles/theme/oc-user-menu.scss
  yarn.lock
Labels: enhancement

#1536 deps: update vue select
  changelog/unreleased/enhancement-bump-vue-select
  package.json
  yarn.lock
Labels: dependencies
