Repository owncloud/owncloud-design-system, pull requests merged in 2021-06, with the labels that each got.

#1368 fix: use correct highlight colour
  changelog/unreleased/bugfix-wrong-selected-bg-colour
  src/styles/theme/background.scss
Labels: bug

#1367 [tests-only] added solar configurations for unit tests
  .drone.star
  sonar-project.properties
Labels: QA:team

#1383 Version bump for release 7.3.0
  changelog/7.3.0_2021-06-14/enhancement-logo-sizing
  package.json
Labels: 3 - To Review

#1391 Enable lint for test spec files
  .eslintignore
  docs/utils/activeNav.spec.js
  docs/utils/filterSearch.spec.js
  docs/utils/statusLabels.spec.js
  src/components/OcBreadcrumb.spec.js
  src/components/OcDrop.spec.js
  src/components/OcModal.spec.js
  src/components/OcProgress.spec.js
  src/components/OcSidebarNav.spec.js
  src/components/OcTag.spec.js
  src/components/avatars/OcAvatarGroup.spec.js
  src/components/pagination/OcPagination.spec.js
  src/components/resource/OcResource.spec.js
  src/components/resource/OcResourceSize.spec.js
  src/components/table/OcTable.sort.spec.js
  src/components/table/OcTableCell.spec.js
  src/components/table/OcTableFiles.spec.js
  src/system.spec.js
Labels: QA:team

#1389 [tests-only] added unit tests for accordion component
  src/components/OcAccordion.spec.js
Labels: QA:team

#1392 [tests-only] add coverage badge
  README.md
Labels: QA:team

#1395 [tests-only] don't count spec files into the coverage
  jest.conf.js
  sonar-project.properties
Labels: QA:team

#1406 ocPagination skip label bugfix
  changelog/unreleased/bugfix-pagination-unnecessary-skip
  src/components/pagination/OcPagination.spec.js
  src/components/pagination/OcPagination.vue
Labels: 3 - To Review, bug

#1407 fix oc-icon name update error
  changelog/unreleased/bugfix-icon-update
  src/components/OcIcon.spec.js
  src/components/OcIcon.vue
Labels: 3 - To Review, bug

#1393 show '--' for negative file size
  changelog/unreleased/bugfix-show-dashes-when-negative-filesize-given
  src/components/resource/OcResourceSize.spec.js
  src/components/resource/OcResourceSize.vue
  src/components/table/OcTableFiles.spec.js
Labels: QA:team

#1415 [ci] rearrange ci steps to optimize runtime
  .drone.star
Labels: 3 - To Review, QA:team

#1419 [ci] Run unit tests before build in CI
  .drone.star
Labels: QA:team

#1410 [unit-tests] Added unit tests for oc app sidebar
  src/components/OcAppSideBar.spec.js
  src/components/OcAppSideBar.vue
Labels: QA:team

#1424 [tests-only] added unit test for oc avatar component
  src/components/avatars/OcAvatar.spec.js
  src/components/avatars/OcAvatar.vue
Labels: QA:team

#1408 Added unit tests for oc checkbox component
  src/components/OcCheckbox.spec.js
Labels: QA:team

#1427 Removed test for default style value
  src/components/avatars/OcAvatar.spec.js
Labels: QA:team

#1428 [tests-only] fail test if console error contains Vue warn
  jest.conf.js
  jest.overrides.js
  src/components/OcButton.spec.js
Labels: QA:team

#1394 Added unit tests for OcActionDrop
  src/components/OcActionDrop.spec.js
  src/components/OcActionDrop.vue
Labels: QA:team

#1430 added unit tests for oc avatar link component
  src/components/avatars/OcAvatarLink.spec.js
Labels: QA:team

#1439 added unit tests for oc dropzone component
  src/components/OcDropzone.spec.js
Labels: QA:team

#1441 added unit tests for OcGrid component
  src/components/OcGrid.spec.js
Labels: QA:team

#1446 added unit tests for OcImage component
  src/components/OcImage.spec.js
Labels: QA:team

#1445 added unit tests for OcHiddenAnnouncer component
  src/components/OcHiddenAnnouncer.spec.js
  src/components/OcHiddenAnnouncer.vue
Labels: QA:team

#1453 Handle initial focus in OcModal
  changelog/unreleased/enhancement-modal-initial-focus
  src/components/OcModal.vue
  src/components/__snapshots__/OcModal.spec.js.snap
Labels: 3 - To Review, enhancement
