Repository owncloud/owncloud-design-system, pull requests merged in 2021-11, with the labels that each got.

#1636 OcTextInput: add defaultValue prop and make clear button null the value
  changelog/unreleased/enhancement-octextinput-props
  src/components/molecules/OcTextInput/OcTextInput.spec.js
  src/components/molecules/OcTextInput/OcTextInput.vue
Labels: 3 - To Review

#1766 introduce closure to mutate resource or file id for dom use only
  changelog/unreleased/enhancement-resource-dom-selector
  src/components/molecules/OcTable/OcTable.spec.js
  src/components/molecules/OcTable/OcTable.vue
  src/components/templates/OcTableFiles/OcTableFiles.spec.js
  src/components/templates/OcTableFiles/OcTableFiles.vue
  src/helpers/constants.js
Labels: 3 - To Review

#1777 Fix drop event & release 11.2.1
  changelog/11.2.1_2021-11-10/bugfix-files-table-drop-event
  package.json
  sonar-project.properties
  src/components/templates/OcTableFiles/OcTableFiles.vue
  src/helpers/constants.js
Labels: 3 - To Review

#1787 Add tooltips to relative dates in files table
  changelog/unreleased/enhancement-add-accentuated-property
  src/components/molecules/OcTable/OcTable.vue
  src/components/templates/OcTableFiles/OcTableFiles.vue
Labels: enhancement

#1782 Truncate file names while preserving file extensions
  changelog/unreleased/enhancement-truncate-file-names
  src/components/atoms/OcResourceName/OcResourceName.vue
  src/components/atoms/OcResourceName/__snapshots__/OcResourceName.spec.js.snap
  src/components/organisms/OcResource/OcResource.vue
Labels: enhancement, 3 - To Review
