Repository owncloud/owncloud-design-system, pull requests merged in 2021-04, with the labels that each got.

#1198 Add vue select
  changelog/unreleased/enhancement-vue-select
  package.json
  src/components/OcSelect.vue
  yarn.lock
Labels: enhancement

#1219 OCTable and OCTableFiles sorting
  changelog/unreleased/enhancement-table-sorting
  src/components/table/OcTable.sort.spec.js
  src/components/table/OcTable.vue
  src/components/table/OcTableFiles.vue
  src/components/table/__snapshots__/OcTableFiles.spec.js.snap
  src/components/table/helpers/constants.js
  src/components/table/mixins/sort.js
  src/components/table/mixins/sort.scss
Labels: 3 - To Review

#1221 revert background color
  src/components/OcAutocomplete.vue
  src/components/OcDropzone.vue
  src/components/OcTag.vue
  src/components/table/OcTable.vue
  src/styles/theme/oc-card.scss
  src/styles/theme/oc-datepicker.scss
  src/styles/theme/oc-file-actions.scss
  src/styles/theme/oc-modal.scss
  src/tokens/ods/color.json
Labels: 3 - To Review

#1225 use yaml as token base
  build/build-tokens.js
  build/build-tokens/format.js
  build/build-tokens/transform.js
  package.json
  src/tokens/docs/border.json
  src/tokens/docs/border.yaml
  src/tokens/docs/font.json
  src/tokens/docs/font.yaml
  src/tokens/docs/line-height.json
  src/tokens/docs/line-height.yaml
  src/tokens/ods/breakpoint.json
  src/tokens/ods/breakpoint.yaml
  src/tokens/ods/color.json
  src/tokens/ods/color.yaml
  src/tokens/ods/font.json
  src/tokens/ods/font.yaml
  src/tokens/ods/size.json
  src/tokens/ods/size.yaml
  src/tokens/ods/space.json
  src/tokens/ods/space.yaml
  src/tokens/ods/z-index.json
  src/tokens/ods/z-index.yaml
  yarn.lock
Labels: 3 - To Review

#1229 Enhance accessibility for the files table and its contents
  changelog/unreleased/enhancement-files-table-a11y
  src/components/OcStatusIndicators.vue
  src/components/resource/OcResource.vue
  src/components/table/OcTableFiles.vue
  src/components/table/__snapshots__/OcTableFiles.spec.js.snap
Labels: accessibility

#1228 Enhance oc-breadcrumb a11y
  changelog/unreleased/change-oc-breadcrumb-a11y
  src/components/OcBreadcrumb.vue
  src/components/__snapshots__/OcBreadcrumb.spec.js.snap
Labels: 3 - To Review, accessibility

#1231 Accessibility improvements on the sidebar component
  changelog/unreleased/change-sidebar-a11y
  src/components/OcSidebar.vue
  src/components/OcSidebarNavItem.vue
Labels: accessibility

#1237 Add modal focus trap
  changelog/unreleased/enhancement-modal-focus-trap
  package.json
  src/components/OcModal.vue
  src/components/__snapshots__/OcModal.spec.js.snap
  yarn.lock
Labels: enhancement

#1239 feat: increase breadcrumbs font size
  changelog/unreleased/enhancement-breadcrumbs-size
  src/components/OcBreadcrumb.vue
Labels: enhancement

#1240 feat: add paddingX prop
  changelog/unreleased/enhancement-table-padding
  src/components/table/OcTable.vue
  src/components/table/OcTableFiles.vue
  src/components/table/__snapshots__/OcTable.spec.js.snap
  src/components/table/__snapshots__/OcTableFiles.spec.js.snap
Labels: enhancement

#1241 A11y improvements
  changelog/unreleased/bugfix-unnecessary-icon-role
  changelog/unreleased/enhancement-accordion-accessibility
  src/components/OcAccordion.vue
  src/components/OcAccordionItem.vue
  src/components/OcIcon.vue
  src/components/OcSidebar.spec.js
  src/components/__snapshots__/OcSidebar.spec.js.snap
  src/components/table/__snapshots__/OcTableFiles.spec.js.snap
Labels: 3 - To Review
