Repository owncloud/owncloud-design-system, pull requests merged in 2021-05, with the labels that each got.

#1269 replace uk-drop by using tippy
  changelog/unreleased/enhancement-oc-drop
  package.json
  src/components/OcDrop.spec.js
  src/components/OcDrop.vue
  src/components/__snapshots__/OcBreadcrumb.spec.js.snap
  src/components/__snapshots__/OcDrop.spec.js.snap
  src/directives/OcTooltip.js
  src/utils/logger.js
  yarn.lock
Labels: 3 - To Review

#1252 Make files table headings more descriptive
  changelog/unreleased/enhancement-files-table-headings
  src/components/table/OcTableFiles.vue
  src/components/table/__snapshots__/OcTableFiles.spec.js.snap
Labels: 3 - To Review, accessibility

#1247 Remove close button on notifications
  changelog/unreleased/enhancement-remove-notification-close-button
  changelog/unreleased/enhancement-show-notification-close-button-via-property
  src/components/OCNotificationMessage.vue
  src/components/OCNotifications.vue
Labels: 3 - To Review, accessibility

#1250 Add description for avatars
  changelog/unreleased/enhancement-avatar-group-description
  jest.setup.js
  src/components/avatars/OcAvatar.vue
  src/components/avatars/OcAvatarGroup.spec.js
  src/components/avatars/OcAvatarGroup.vue
  src/components/avatars/__snapshots__/OcAvatarGroup.spec.js.snap
  src/components/table/OcTableFiles.vue
  src/components/table/__snapshots__/OcTableFiles.spec.js.snap
Labels: 3 - To Review, accessibility

#1300 feat: rename sidebar to sidebar-nav, use fc and switch to slots instead of props
  changelog/unreleased/change-rename-sidebar
  changelog/unreleased/change-slots-in-sidebar
  changelog/unreleased/enhancement-button-inverse-variant
  src/components/OcButton.vue
  src/components/OcList.vue
  src/components/OcLogo.vue
  src/components/OcSearchBar.vue
  src/components/OcSidebar.spec.js
  src/components/OcSidebar.vue
  src/components/OcSidebarNav.spec.js
  src/components/OcSidebarNav.vue
  src/components/OcSidebarNavItem.vue
  src/components/__snapshots__/OcSidebar.spec.js.snap
  src/styles/styles.scss
  src/styles/theme/background.scss
  src/styles/theme/oc-button.scss
  src/styles/theme/oc-sidebar.scss
  src/tokens/ods/color.yaml
Labels: enhancement

#1308 fix: make OcSidebarNavItem text bold again
  changelog/unreleased/bugfix-make-sidebar-navitem-bold
  src/components/OcSidebarNavItem.vue
Labels: bug

#1302 a11y color contrasts
  .codacy.yml
  .drone.star
  README.md
  build/build-tokens.js
  build/build-tokens/format-report-color-contrast.js
  build/build-tokens/format-writer-json.js
  build/build-tokens/format-writer-scss.js
  build/build-tokens/format.js
  build/build-tokens/transform-color.js
  build/build-tokens/transform-namespace.js
  build/build-tokens/transform.js
  build/build-tokens/utils.js
  changelog/unreleased/enhancement-a11y-color-contrasts
  src/components/OCNotificationMessage.vue
  src/components/OcButton.vue
  src/components/avatars/OcAvatar.vue
  src/components/avatars/OcAvatarLink.vue
  src/styles/theme/oc-datepicker.scss
  src/tokens/ods/color.yaml
Labels: 3 - To Review

#1309 feat: add sort button to table header cells
  changelog/unreleased/bugfix-table-header-height
  changelog/unreleased/enhancement-use-btn-to-sort
  src/components/table/OcTable.sort.spec.js
  src/components/table/OcTable.spec.js
  src/components/table/OcTable.vue
  src/components/table/OcTableFiles.spec.js
  src/components/table/_OcTableCellHead.vue
  src/components/table/__snapshots__/OcTable.spec.js.snap
  src/components/table/__snapshots__/OcTableFiles.spec.js.snap
  src/components/table/mixins/sort.js
  src/components/table/mixins/sort.scss
Labels: accessibility, enhancement

#1310 Change OcSidebarNav active and hover colors
  changelog/unreleased/enhancement-active-nav
  src/components/OcSidebarNavItem.vue
Labels: 3 - To Review, accessibility

#1319 reduce fileslist row height
  changelog/unreleased/enhancement-reduce-fileslist-row-height
  src/components/table/_OcTableCell.vue
  src/tokens/ods/size.yaml
Labels: enhancement

#1333 feat: apply css custom props to host
  build/build-tokens/format-writer-scss.js
  changelog/unreleased/enhancement-host-props
Labels: enhancement
